function y = hpf_lpf(x,~)
%  Preprocess input x
%    This function expects an input vector x and a vector of time values
%    tx. tx is a numeric vector in units of seconds.

% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 21-Sep-2023 01:19:47

Fs = 500; % Average sample rate
y = highpass(x,0.5,Fs,'Steepness',0.75,'StopbandAttenuation',70);

y = lowpass(y,10,Fs,'Steepness',0.75,'StopbandAttenuation',70);