function y = hpf_lpf(x,fs)
%  Preprocess input x
%    This function expects an input vector x and a vector of time values
%    tx. tx is a numeric vector in units of seconds.

% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 21-Sep-2023 01:19:47

y = highpass(x,0.4,fs,'Steepness',0.80,'StopbandAttenuation',70);

y = lowpass(y,10,fs,'Steepness',0.80,'StopbandAttenuation',70);